version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"

phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install docker.io -y
  build:
    commands:
    - echo building the justiceleague-tracker
    - docker build -t abc:latest .
    - docker tag abc:latest xxxxxx.dkr.ecr.ap-south-1.amazonaws.com/abc:latest
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin xxxxxx.dkr.ecr.ap-south-1.amazonaws.com
    - docker push xxxxx.dkr.ecr.ap-south-1.amazonaws.com/abc:latest
artifacts:
  files:
  - target/*.jar
  - scripts/*.sh
  - appspec.yml
  discard-paths: yes

cache:
  paths:
  - '/root/.m2/**/*'
